language: cpp
sudo: required
dist: trusty
branches:
  only:
    - master
os:
  - linux

env:
  - CONFIG=Release MIDIEDITOR_RELEASE_VERSION_ID=2 MIDIEDITOR_RELEASE_VERSION_STRING=3.1.0 MIDIEDITOR_PACKAGE_VERSION=1 MIDIEDITOR_BINARY=MidiEditor

before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
    - sudo apt-get install qt5-default qttools5-dev-tools
    - QT_VERSION_MM=59
    - QT_VERSION_FULL=591-trusty
    - sudo apt-get install libsfml-dev
    - sudo apt-get install libasound2-dev
    - sudo apt-get install curl
    - sudo apt-get install fakeroot
    
before_script:

script:
   - qmake -qt=qt5 -project -v
   - qmake -qt=qt5 midieditor.pro
   - make
   - sh packaging/unix/build_deb.sh
   - ls -la

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: deb
