language: cpp
sudo: required
dist: trusty
branches:
  only:
    - master
os:
  - linux

env:
  - CONFIG=Release

before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
    - sudo apt-get install qt5-default qttools5-dev-tools
    - QT_VERSION_MM=59
    - QT_VERSION_FULL=591-trusty
    - sudo apt-get install libsfml-dev
    - sudo apt-get install libasound2-dev
    - sudo apt-get install curl
    
before_script:

script:
   - qmake -project
   - qmake midieditor.pro
   - make

