language: cpp
sudo: required
dist: trusty
branches:
  only:
    - master
os:
  - linux

env:
  - CONFIG=Release MIDIEDITOR_RELEASE_VERSION_ID=2 MIDIEDITOR_RELEASE_VERSION_STRING=3.1.0 MIDIEDITOR_PACKAGE_VERSION=1 MIDIEDITOR_BINARY=MidiEditor MXE=mxe PATH=$MXE/usr/bin:$PATH

before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
    - sudo apt-get install qt5-default qttools5-dev-tools
    - QT_VERSION_MM=59
    - QT_VERSION_FULL=591-trusty
    - sudo apt-get install libsfml-dev
    - sudo apt-get install libasound2-dev
    - sudo apt-get install curl
    - sudo apt-get install fakeroot
    # For mxe.cc (see http://mxe.cc/#requirements)
    - sudo apt-get install autoconf automake autopoint bash bison bzip2 flex g++ g++-multilib gettext git gperf intltool libc6-dev-i386 libgdk-pixbuf2.0-dev libltdl-dev libssl-dev libtool libxml-parser-perl make openssl p7zip-full patch perl pkg-config python ruby scons sed unzip wget xz-utils
    
before_script:

script:
   - sh building/build-linux.sh
   - sh packaging/unix/build_deb.sh
   - git clone https://github.com/mxe/mxe.git mxe
   - travis_wait 60 cd mxe && make qtbase && cd ..
   - sh building/build-windows.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: local
  master-dir: deb
